```{r}
library(ape)
n <- 750

tree <- rtree(n)
clump1 <- sample(0:1, n, replace = TRUE)
clump2a <- sample(0:1, n, replace = TRUE)
clump2b <- sample(0:1, n, replace = TRUE)
clump4 <- sample(0:1, n, replace = TRUE)
even <- sample(0:1, n, replace = TRUE)
random <- sample(0:1, n, replace = TRUE)
samp <- data.frame(
        clump1,
        clump2a,
        clump2b,
        clump4,
        even,
        random
)
samp <- t(samp)

colnames(samp) <- tree$tip.label

##print(cophenetic(tree))
```

```{r}
mpd.ori <- function(samp, dis, abundance.weighted = FALSE) {
  N <- dim(samp)[1] ## le nombre de row
  mpd <- numeric(N) ## N en liste de N objets
  for (i in 1:N) {
    sppInSample <- names(samp[i, samp[i,] > 0]) ## prend les rows avec des espèces présentes
    if (length(sppInSample) > 1) { ## si plus de 1
      sample.dis <- dis[sppInSample, sppInSample] ##les distances en tableau croisé
      if (abundance.weighted) {
        sample.weights <- t(as.matrix(samp[i, sppInSample, drop = FALSE])) %*% as.matrix(samp[i, sppInSample, drop = FALSE])
        mpd[i] <- weighted.mean(sample.dis, sample.weights)
      } else {
        mpd[i] <- mean(sample.dis[lower.tri(sample.dis)])
      }
    } else {
      mpd[i] <- NA
    }
  }
  mpd
}
##system.time(mpd.ori(samp, cophenetic(tree), abundance.weighted = FALSE))
result <- mpd.ori(samp, cophenetic(tree), abundance.weighted = TRUE)
print(result)
```
```{r}

library("microbenchmark")
library(ggplot2)
bench<-
        microbenchmark(
      'nouvelle version' = mpdn(samp, cophenetic(tree), abundance.weighted = FALSE),
     'originale' =   mpd.ori(samp, cophenetic(tree), abundance.weighted = FALSE)
)

bench
autoplot2(bench)+ theme(axis.title.x = element_text(size = 20),
                        axis.text = element_text(size = 20,face = 'bold' ),
                        axis.title.y = element_text(size = 10))
##theme(panel.background = element_rect(fill = "#67c9ff"))
##ggplot(bench)+geom_boxplot(aes( x = expr, y = time), outlier.shape = NA)+ ylim(0,1e+07)
```

```{r}
##system.time(mpdn(samp, cophenetic(tree), abundance.weighted = FALSE))
##system.time(mpd.ori(samp, cophenetic(tree), abundance.weighted = FALSE))
library(microbenchmark)
plot(

        microbenchmark(
mpdn(samp, cophenetic(tree), abundance.weighted = FALSE),
mpd.ori(samp, cophenetic(tree), abundance.weighted = FALSE)
))

```


```{r}
mpdn<-function(sample, distance, abundance.weighted = FALSE)
{
  if(sum(colnames(sample)!=rownames(distance))>0)
  {
    sp.name <- intersect(colnames(sample), rownames(distance))
    sample <- sample[, match(sp.name, colnames(sample))]
    distance <- distance[match(sp.name, rownames(distance)), match(sp.name, rownames(distance))]
  }
  comt <- sample
  if(!abundance.weighted)
  {
    comt[comt>0] <- 1
    num <- rowSums(comt)
  }
  comt <- comt/rowSums(comt)
  comt <- as.matrix(comt)
  distance <- as.matrix(distance)
  comd <- comt %*% distance
  res <- comd * comt
  res <- rowSums(res)
  if(!abundance.weighted)
  {
    res <- res*(num/(num-1))
  }
  names(res)<-NULL
  res
}

mpdn(samp, cophenetic(tree), abundance.weighted = TRUE)

```

```{r}
rsample <-function (maximum,tree, all_NA = FALSE, column_with_NA = FALSE
){
  tree.lenth <- length(tree$tip.label)
  clump1 <- sample(0:maximum, tree.lenth, replace = TRUE)
  clump2a <- sample(0:maximum, tree.lenth, replace = TRUE)
  clump2b <- sample(0:maximum, tree.lenth, replace = TRUE)
  clump4 <- sample(0:maximum, tree.lenth, replace = TRUE)
  even <- sample(0:maximum, tree.lenth, replace = TRUE)
  random <- sample(0:maximum,tree.lenth, replace = TRUE)
  samp <- data.frame(
          clump1,
          clump2a,
          clump2b,
          clump4,
          even,
          random
  )

  samp <- t(samp)

  if (all_NA == TRUE)
  {
    samp[]<-NA
  }
  if(column_with_NA){
    samp[, column_with_NA] <- NA



  }
  colnames(samp) <- tree$tip.label


  samp

}

tree <-rtree(50)

print(length(tree$tip.label))


exemple <-rsample(25,tree)
print(exemple)

rownames(exemple)

li <-c("clump1","clump2a","clump2b","clump4","even","random" )

print(identical(rownames(exemple),li))

```
```{r}
datasetsVerification <- function(dataset){


  if (any(is.na(dataset))) {
    print("There are NAs in the dataset")
  }
     else {
    print("The dataset seem correct")
  }
}

```
```{r}
library(ggplot2)
# Vecteur de données
data <- c(2, 30, 59, 113, 145, 189, 221, 233, 259, 294, 401, 476, 563, 634, 568)

# Séquence de dates
#date <- seq(2009, 2023)
date <- seq(as.Date("2009-01-01"), as.Date("2023-01-01"), by = "year")


# Créer un data.frame avec le vecteur de données
citation <- data.frame(date,data)

# Attribuer les dates comme noms de lignes
##rownames(citation) <- as.character(date)

# Convertir les noms de lignes en dates
##citation$date <- as.Date(rownames(citation), format = "%Y")

# Tracer les données en fonction des dates
##plot(citation$date, citation$data, type = "o", main = "Données en fonction des dates", xlab = "Date", ylab = "Données")

ggplot(citation, aes(x = date, y = data)) +
  geom_line() +
  geom_point()



```
```{r}
autoplot2<-function (object, ..., log = TRUE, y_max = NULL)
{
  if (!requireNamespace("ggplot2"))
          stop("Missing package 'ggplot2'.")
  y_min <- 0
  object$ntime <- convert_to_unit(object$time, "t")
  if (is.null(y_max)) {
    y_max <- max(object$ntime)
  }
  plt <- ggplot2::ggplot(object, ggplot2::aes_string(x = "expr",
                                                     y = "ntime"))
  plt <- plt + ggplot2::stat_ydensity()
  plt <- plt + ggplot2::scale_x_discrete(name = "")
  y_label <- sprintf("Temps [%s]", attr(object$ntime,
                                       "unit"))
  if (log) {
    y_min <- if (min(object$time) == 0)
            1
    else min(object$ntime)
    plt <- plt + ggplot2::scale_y_log10(name = y_label)
  }
  else {
    plt <- plt + ggplot2::scale_y_continuous(name = y_label)
  }
plt <- plt + ggplot2::coord_flip(ylim = c(y_min, y_max))


  plt
}

convert_to_unit <- function(x,
                            unit=c("ns", "us", "ms", "s", "t",
                                   "hz", "khz", "mhz", "eps", "f")) {
  unit <- match.arg(unit)

  switch (unit,
          t=unit <- sprintf ("%ss", find_prefix(x * 1e-9,
                                                minexp = -9, maxexp = 0, mu = FALSE)),
          f=unit <- sprintf ("%shz", find_prefix(1e9 / x,
                                                 minexp =  0, maxexp = 6, mu = FALSE))
  )
  unit <- tolower(unit)
  switch (unit,
          ns  ={attr(x, "unit") <- "nanoseconds"           ; unclass(x      )},
          us  ={attr(x, "unit") <- "microseconds"          ; unclass(x / 1e3)},
          ms  ={attr(x, "unit") <- "millisecondes"          ; unclass(x / 1e6)},
          s   ={attr(x, "unit") <- "seconds"               ; unclass(x / 1e9)},
          eps ={attr(x, "unit") <- "evaluations per second"; unclass(1e9 / x)},
          hz  ={attr(x, "unit") <- "hertz"                 ; unclass(1e9 / x)},
          khz ={attr(x, "unit") <- "kilohertz"             ; unclass(1e6 / x)},
          mhz ={attr(x, "unit") <- "megahertz"             ; unclass(1e3 / x)},
          stop("Unknown unit '", unit, "'.")
  )
}

find_prefix <- function (x, f=min, minexp=-Inf, maxexp=Inf, mu=TRUE) {
  prefixes <- c ("y", "z", "a", "f", "p", "n", "u", "m", "",
                 "k", "M", "G", "T", "P", "E", "Z", "Y")
  if (mu) prefixes [7] <- "\u03bc"

  if (is.numeric (minexp)) minexp <- floor (minexp / 3)
  if (is.numeric (minexp)) maxexp <- floor (maxexp / 3)

  e3 <- floor (log10 (f (x)) / 3)
  e3 <- max (e3, minexp, -8) # prefixes go from 10^-24 = 10^(3 * -8)
  e3 <- min (e3, maxexp,  8) # to 10^24 = 10^(3 * 8)

  prefixes [e3 + 9] # e3 of -8 => index 1
}
```
```{r}

 randtree <- rcoal(20)
randtraits <- rTraitCont(randtree)
typeof(randtraits[randtree$tip.label])
typeof(randtraits)
sample <-randtraits[randtree$tip.label]
sample <-as.data.frame(sample)
is.data.frame(sample)
phylosignal(sample,randtree)

```
```{r}
phylostruct(phylocom$sample,phylocom$phylo, metric = 'psv')

```
```{r}

datasetsVerification <- function(dataset){
  isGood <- TRUE
  if (!is.data.frame(dataset)){
    print("The dataset is not an dataframe")
    isGood <- FALSE
  }
  if (all(dim(df) == c(0, 0))) {
    print("The dataset is empty")
    isGood <- FALSE
  }
  if (any(is.na(dataset))) {
    print("There are NAs in the dataset")
    isGood <- FALSE
  }
  if (any(sapply(df, function(x) any(is.character(x))))) {
    print("There are characters in the dataset")
    isGood <-FALSE
  }
  if (isGood) {
    print("The dataset seem correct")
  }
}

a <- c(10,20,30,40)
b <- c('book', NA, 'textbook', 'pencil_case')
c <- c(TRUE,FALSE,TRUE,FALSE)
d <- c(2.5, 8, 10, 7)
df <- data.frame(a,b,c,d)

df <-as.matrix(df)

datasetsVerification(df)

```
```{r}
randtree <- rcoal(20)
randtraits <- rTraitCont(randtree)
 phylosignal(randtraits[randtree$tip.label],randtree)

```

** MNTD **
```{r}

mntd.new<-function(comm, pd, abundance.weighted = TRUE) {
  pd <- as.matrix(pd)
  N <- nrow(comm)
  id <- (comm > 0)
  diag(pd) <- NA
  gc()
  if (abundance.weighted) {
    min.d <- matrix(0, nrow = N, ncol = ncol(comm))
    for (i in 1 : N) {
      pdx <- pd[id[i, ], id[i, ], drop = FALSE]
      if (nrow(pdx) > 1) {
        min.d[i, id[i, ]] <- apply(pdx, 2, min, na.rm = TRUE)
      }
    }
    comm.p <- comm / rowSums(comm)
    res <- min.d * comm.p
    res <- rowSums(res)
  } else {
    res <- comm[, 1]
    for (i in 1 : N) {
      pdx <- pd[id[i, ], id[i, ], drop = FALSE]
      res[i] <- mean(apply(pdx, 2, min, na.rm = TRUE))
    }
  }

  names(res) <- rownames(comm)
  res
}
```
