# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distmat_rcpp <- function(comm, dis, threads = 1L) {
    .Call(`_picante_distmat_rcpp`, comm, dis, threads)
}

